### PR TITLE
Add support for functions when calling mocks

### PR DESCRIPTION
**Pull request by deitch**
Instead of just fixed `data` as the third argument to `mock()`, it can be fixed or functions. This gives the ability to look at parameters, provide variable data, send data or call an error.

### CODE REVIEW

**Comment by deitch** [comment]
Added one test for the function. All tests that passed before, pass now.

**Comment by hairyhenderson** [comment]
@deitch - nice. Was just wondering if there was a way I could inject errors, and this looks like the right way!

@antonosmond - any chance of this getting merged soon?

**Comment by antonosmond** [comment]
Done - only just saw your pull request otherwise I would've merged it sooner. Tbh I've not used this repo for a while but if people are using it I'll keep it alive and merge any sensible changes. Thanks for your contribution @deitch - have a great Xmas!

**Comment by hairyhenderson** [comment]
:tada: @antonosmond - are you going to publish the new version to npmjs?

**Comment by antonosmond** [comment]
@hairyhenderson - Done.

**Comment by hairyhenderson** [comment]
@antonosmond - awesome, thank you! :)

**Comment by deitch** [comment]
Great! I am glad it was helpful to people.

**Pull request merged**
